### Profile
POST http://localhost:8080/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlaXMiOjM2MDAsImV4cCI6MTc2NzkzMTYwMCwiaWlkIjoiaW5zXzM4MDhTY1lBQmdqMGN6QkFNTFFiRklXVEpHWiIsInNpZCI6ImFjdF8zODBFSFh1SVdxbmZvWEZwcDQwTlZNMkI0cmoiLCJzdCI6ImFjdG9yX3Rva2VuIn0.m8ujfA0dmLCzKp4HcZXqQCJ7NdBwdk4Kp9qZbubS-AWCTQ2VwE94-BV8OjG0EG5MsyCZmwa12EYuaOB-f-xpGq9Fu--aGR_6DQUyoZT-E-Slk5bLH5CPsaJaVGh5vcFBQxRKwvE1Rho0UoJjqVTkUZ6L9E8dtPwF0mOfZ5IKUGqVUWmZ5WHm6TrLK_dOLxMjbvZ6XpeNo9pDyLEbkY8xGmAH9SWJdO9sC19r6qL4OXLuC3Jdr65VVbVrIyoVNk3As38Fzyc6P5Cztre6VncK9YTmb5X0e9iyWcyTPhhEq75SPSXdtHraqkZEArxQeIKaS8cFx5X5Tb1RYUtJ3MSWgQ

{
    "name":"Huu"
}

### GET Categories
GET http://localhost:8080/categories

### GET Products
GET http://localhost:8080/products?query=brews

### GET Products pagination
GET http://localhost:8080/products?pageSize=2&page=2


### GET Product By ID
GET http://localhost:8080/products/1

### DELETE Product By ID
DELETE http://localhost:8080/products/a
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3Njg5ODIxOTAsImlhdCI6MTc2ODM3NzM5MCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI5MGJmOTQxNmQwOThhZTI5ODA4YiIsIm5iZiI6MTc2ODM3NzM4NSwib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4RW9rMGtlVG1XRXRQMG1yRzAzdTJVWDNEViJ9.V1GpAJTRfSP0RP2jUduDJyH-SehWIGYVsP9cmHCEv2W1KwezXR9Bl3clgt2dVh9a91Mcgbt8msaGYT_9OkqSIiSS73kwrcUtikROk0akvVLLGHdKEIvoC7EoeivLsGNGjSVh-FvcqBsltkvM2Mt6fz0WrrcTxYUeng30wLM9_fEAhZOxd_21Cxr8ckkaBRcwE0v711yPajluzy8yTCE5BbrmRAuUbwsx_EsxkicMs2BbDLOYXFaE0LqSJMrKz9mWFWEwH1NTxQISV4XUaiyWBEHKE3ADgNGiCGU7HO1KhUpQ5LriAb__Hjx0REStL5B8Zm-pi7HIXTZanZuonmLLBw


### POST Products
POST http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3Njg5ODIxOTAsImlhdCI6MTc2ODM3NzM5MCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI5MGJmOTQxNmQwOThhZTI5ODA4YiIsIm5iZiI6MTc2ODM3NzM4NSwib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4RW9rMGtlVG1XRXRQMG1yRzAzdTJVWDNEViJ9.V1GpAJTRfSP0RP2jUduDJyH-SehWIGYVsP9cmHCEv2W1KwezXR9Bl3clgt2dVh9a91Mcgbt8msaGYT_9OkqSIiSS73kwrcUtikROk0akvVLLGHdKEIvoC7EoeivLsGNGjSVh-FvcqBsltkvM2Mt6fz0WrrcTxYUeng30wLM9_fEAhZOxd_21Cxr8ckkaBRcwE0v711yPajluzy8yTCE5BbrmRAuUbwsx_EsxkicMs2BbDLOYXFaE0LqSJMrKz9mWFWEwH1NTxQISV4XUaiyWBEHKE3ADgNGiCGU7HO1KhUpQ5LriAb__Hjx0REStL5B8Zm-pi7HIXTZanZuonmLLBw

{
    "name":"Product",
    "description":"description",
    "price":500.9,
    "stock":200,
    "category":"Electronics"
}

### Add Product to Cart 
POST http://localhost:8080/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3Njg5ODIxOTAsImlhdCI6MTc2ODM3NzM5MCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI5MGJmOTQxNmQwOThhZTI5ODA4YiIsIm5iZiI6MTc2ODM3NzM4NSwib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4RW9rMGtlVG1XRXRQMG1yRzAzdTJVWDNEViJ9.V1GpAJTRfSP0RP2jUduDJyH-SehWIGYVsP9cmHCEv2W1KwezXR9Bl3clgt2dVh9a91Mcgbt8msaGYT_9OkqSIiSS73kwrcUtikROk0akvVLLGHdKEIvoC7EoeivLsGNGjSVh-FvcqBsltkvM2Mt6fz0WrrcTxYUeng30wLM9_fEAhZOxd_21Cxr8ckkaBRcwE0v711yPajluzy8yTCE5BbrmRAuUbwsx_EsxkicMs2BbDLOYXFaE0LqSJMrKz9mWFWEwH1NTxQISV4XUaiyWBEHKE3ADgNGiCGU7HO1KhUpQ5LriAb__Hjx0REStL5B8Zm-pi7HIXTZanZuonmLLBw

{
    "name":"Product",
    "description":"description",
    "price":500.9,
    "stock":200,
    "category":"Electronics"
}

### Get Cart 
GET http://localhost:8080/cart
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3Njg5ODIxOTAsImlhdCI6MTc2ODM3NzM5MCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI5MGJmOTQxNmQwOThhZTI5ODA4YiIsIm5iZiI6MTc2ODM3NzM4NSwib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4RW9rMGtlVG1XRXRQMG1yRzAzdTJVWDNEViJ9.V1GpAJTRfSP0RP2jUduDJyH-SehWIGYVsP9cmHCEv2W1KwezXR9Bl3clgt2dVh9a91Mcgbt8msaGYT_9OkqSIiSS73kwrcUtikROk0akvVLLGHdKEIvoC7EoeivLsGNGjSVh-FvcqBsltkvM2Mt6fz0WrrcTxYUeng30wLM9_fEAhZOxd_21Cxr8ckkaBRcwE0v711yPajluzy8yTCE5BbrmRAuUbwsx_EsxkicMs2BbDLOYXFaE0LqSJMrKz9mWFWEwH1NTxQISV4XUaiyWBEHKE3ADgNGiCGU7HO1KhUpQ5LriAb__Hjx0REStL5B8Zm-pi7HIXTZanZuonmLLBw

