### Profile
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "identifier":"huuduv2@gmail.com",
    "password":"adhg3166@D"
}

### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "identifier":"huuduv2@gmail.com",
    "password":"adhg3166@D"
}

### GET Categories
GET http://localhost:8080/api/v1/categories

### GET Products
GET http://localhost:8080/api/v1/products?query=b

### GET Products pagination
GET http://localhost:8080/api/v1/products?pageSize=2&page=2


### GET Product By ID
GET http://localhost:8080/api/v1/products/5263

### DELETE Product By ID
DELETE http://localhost:8080/api/v1/products/5263
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3NjkwNTI4MDgsImlhdCI6MTc2ODQ0ODAwOCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiJhMWZhMWM2ZmUxMTdkZWJkMThkNCIsIm5iZiI6MTc2ODQ0ODAwMywib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4SDkwM1Q0QWM5S2tWN2hIM0gyQktVTzJ0OCJ9.PTEgu1l-LqKiR0ZaNEftKgppnTmGc79gE4KY3FIQzleZqD40sEuO5FxcHa6wfcY0KmUeA25u2gLSzkuZV4b5_W0C6Ig6l65gtsnFRWyd1udHoudYEBcapk0i8jYRDbOiNaMl9iLn6iajXJdjl95ZpyD1qb4dy4Fv0yOrXIFzZoZW7RCYDISV_wnEcgAFvH0ZXW1qg0hgopRcNAJZV4haqCY_CWV-K8Lyf3z5cXkjMB4klwtxNwhCiifR0rI-SJ10eLKTz5HP8D5OoflDjYKsPCvy_bihUTDMXvnzRQz2HhUJUz-Q-zNI0b3Hz7BqHbSsoA9nxCJ-irqD7z4OrakC2g


### POST Products
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3NjkwNTI4MDgsImlhdCI6MTc2ODQ0ODAwOCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiJhMWZhMWM2ZmUxMTdkZWJkMThkNCIsIm5iZiI6MTc2ODQ0ODAwMywib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4SDkwM1Q0QWM5S2tWN2hIM0gyQktVTzJ0OCJ9.PTEgu1l-LqKiR0ZaNEftKgppnTmGc79gE4KY3FIQzleZqD40sEuO5FxcHa6wfcY0KmUeA25u2gLSzkuZV4b5_W0C6Ig6l65gtsnFRWyd1udHoudYEBcapk0i8jYRDbOiNaMl9iLn6iajXJdjl95ZpyD1qb4dy4Fv0yOrXIFzZoZW7RCYDISV_wnEcgAFvH0ZXW1qg0hgopRcNAJZV4haqCY_CWV-K8Lyf3z5cXkjMB4klwtxNwhCiifR0rI-SJ10eLKTz5HP8D5OoflDjYKsPCvy_bihUTDMXvnzRQz2HhUJUz-Q-zNI0b3Hz7BqHbSsoA9nxCJ-irqD7z4OrakC2g

{
    "name":"Product",
    "description":"description",
    "price":500.9,
    "stock":200,
    "category":"Electronics"
}

### Add Product to Cart 
POST http://localhost:8080/api/v1/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Njk3NjA1NzksImlhdCI6MTc2OTE1NTc3OSwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiIyYzhmY2I1NjJkODFlMjZiN2RhNyIsIm5iZiI6MTc2OTE1NTc3NCwib3JnUm9sZSI6bnVsbCwicm9sZSI6bnVsbCwic3ViIjoidXNlcl8zOGVEaXZRQXljaUNPNjJTYlhlNm9hUTN1UlcifQ.nff6rcqhtwfSaF103MJnbptg2uQFveiDqQZrzTo6nHSMcCTlkxyEynitubFIoIjOFOy7gEMbAC1b356qg_6i0l2RrNeD1RqWM7kQW8hdHc13IcHWFbyWDn9h84syHMbW4tsrrAZHRPTinZ1HLy3898RJJ6dgrFwAM3S_q6u4v4_gbrgoei9wnzzItQF1tHw5a91R_lLZzR5UvIh2fzhkGHAeo30_y1hvSY0KBBESbA-Ukf9LEuw79rIDeNFEv9MMM10R-rBlmRfPmxraRZjb_DpGvGW835CpG8ugVe87Avb9HMnJpQXCdYSRa6kZT6ZVDs5AbdzjjD1JWoFyfWMIXA

{
    "productId":5264,
    "quantity":12
}

### Get Cart 
GET http://localhost:8080/api/v1/cart
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Njk3NjA1NzksImlhdCI6MTc2OTE1NTc3OSwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiIyYzhmY2I1NjJkODFlMjZiN2RhNyIsIm5iZiI6MTc2OTE1NTc3NCwib3JnUm9sZSI6bnVsbCwicm9sZSI6bnVsbCwic3ViIjoidXNlcl8zOGVEaXZRQXljaUNPNjJTYlhlNm9hUTN1UlcifQ.nff6rcqhtwfSaF103MJnbptg2uQFveiDqQZrzTo6nHSMcCTlkxyEynitubFIoIjOFOy7gEMbAC1b356qg_6i0l2RrNeD1RqWM7kQW8hdHc13IcHWFbyWDn9h84syHMbW4tsrrAZHRPTinZ1HLy3898RJJ6dgrFwAM3S_q6u4v4_gbrgoei9wnzzItQF1tHw5a91R_lLZzR5UvIh2fzhkGHAeo30_y1hvSY0KBBESbA-Ukf9LEuw79rIDeNFEv9MMM10R-rBlmRfPmxraRZjb_DpGvGW835CpG8ugVe87Avb9HMnJpQXCdYSRa6kZT6ZVDs5AbdzjjD1JWoFyfWMIXA

### Delete Cart
DELETE http://localhost:8080/cart/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3NjkwNTI4MDgsImlhdCI6MTc2ODQ0ODAwOCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiJhMWZhMWM2ZmUxMTdkZWJkMThkNCIsIm5iZiI6MTc2ODQ0ODAwMywib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4SDkwM1Q0QWM5S2tWN2hIM0gyQktVTzJ0OCJ9.PTEgu1l-LqKiR0ZaNEftKgppnTmGc79gE4KY3FIQzleZqD40sEuO5FxcHa6wfcY0KmUeA25u2gLSzkuZV4b5_W0C6Ig6l65gtsnFRWyd1udHoudYEBcapk0i8jYRDbOiNaMl9iLn6iajXJdjl95ZpyD1qb4dy4Fv0yOrXIFzZoZW7RCYDISV_wnEcgAFvH0ZXW1qg0hgopRcNAJZV4haqCY_CWV-K8Lyf3z5cXkjMB4klwtxNwhCiifR0rI-SJ10eLKTz5HP8D5OoflDjYKsPCvy_bihUTDMXvnzRQz2HhUJUz-Q-zNI0b3Hz7BqHbSsoA9nxCJ-irqD7z4OrakC2g

### Delete Cart Item
DELETE http://localhost:8080/api/v1/cart/items/2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3NjkwNTI4MDgsImlhdCI6MTc2ODQ0ODAwOCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiJhMWZhMWM2ZmUxMTdkZWJkMThkNCIsIm5iZiI6MTc2ODQ0ODAwMywib3JnX3JvbGUiOiJvcmc6YWRtaW4iLCJzdWIiOiJ1c2VyXzM4SDkwM1Q0QWM5S2tWN2hIM0gyQktVTzJ0OCJ9.PTEgu1l-LqKiR0ZaNEftKgppnTmGc79gE4KY3FIQzleZqD40sEuO5FxcHa6wfcY0KmUeA25u2gLSzkuZV4b5_W0C6Ig6l65gtsnFRWyd1udHoudYEBcapk0i8jYRDbOiNaMl9iLn6iajXJdjl95ZpyD1qb4dy4Fv0yOrXIFzZoZW7RCYDISV_wnEcgAFvH0ZXW1qg0hgopRcNAJZV4haqCY_CWV-K8Lyf3z5cXkjMB4klwtxNwhCiifR0rI-SJ10eLKTz5HP8D5OoflDjYKsPCvy_bihUTDMXvnzRQz2HhUJUz-Q-zNI0b3Hz7BqHbSsoA9nxCJ-irqD7z4OrakC2g



###

POST https://saundra-unawarded-shirlee.ngrok-free.dev/api/v1/checkout/webhooks
Content-Type: application/json

{
    
}


### Get Order 
GET http://localhost:8080/api/v1/orders?page=2&pageSize=1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Njk3NjA1NzksImlhdCI6MTc2OTE1NTc3OSwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiIyYzhmY2I1NjJkODFlMjZiN2RhNyIsIm5iZiI6MTc2OTE1NTc3NCwib3JnUm9sZSI6bnVsbCwicm9sZSI6bnVsbCwic3ViIjoidXNlcl8zOGVEaXZRQXljaUNPNjJTYlhlNm9hUTN1UlcifQ.nff6rcqhtwfSaF103MJnbptg2uQFveiDqQZrzTo6nHSMcCTlkxyEynitubFIoIjOFOy7gEMbAC1b356qg_6i0l2RrNeD1RqWM7kQW8hdHc13IcHWFbyWDn9h84syHMbW4tsrrAZHRPTinZ1HLy3898RJJ6dgrFwAM3S_q6u4v4_gbrgoei9wnzzItQF1tHw5a91R_lLZzR5UvIh2fzhkGHAeo30_y1hvSY0KBBESbA-Ukf9LEuw79rIDeNFEv9MMM10R-rBlmRfPmxraRZjb_DpGvGW835CpG8ugVe87Avb9HMnJpQXCdYSRa6kZT6ZVDs5AbdzjjD1JWoFyfWMIXA


### Get Order 
POST http://localhost:8080/api/v1/create-payment-intent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDIyMkFBQSIsImtpZCI6Imluc18zODA4U2NZQUJnajBjekJBTUxRYkZJV1RKR1oiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3Njk3NTg0NjQsImlhdCI6MTc2OTE1MzY2NCwiaXNzIjoiaHR0cHM6Ly9wcm9iYWJsZS1nb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYiLCJqdGkiOiI0ZjllOGQ3YTYxZDc5ZWE2Nzk5YyIsIm5iZiI6MTc2OTE1MzY1OSwib3JnX3JvbGUiOm51bGwsInN1YiI6InVzZXJfMzhlRGl2UUF5Y2lDTzYyU2JYZTZvYVEzdVJXIn0.M1_9q86ECpENxdLSIE5IRV8eopG4GCD2VICPolXJsYIorT7rT_7HuGhizm8rpGE5BbrAsUnKaxImqvYTpigISzz8yY113ehqKnk2APSQ7Rcw9Z9pgXFuM2HlRUEMHgGxmBn1qhsYYsugOrvl7mM_dC5ENNzoIc1X_JgYcrpc9CJ5FAIBBzV_fjIZ70TwSMbqSf9xcFTbVb81PovJoAHIpB0_n04F0tMNN0-i1lQ5YXxqLZMD9EnPVHMgO7-oGX7etNxexfzad0pcxudW6Y6ODBJLtWS8AMvEAsn2RO7AX2cnsHDzQjp0IhJSHaiRYsf9lpX0NiujWPezw98b3gs1yQ

{
   "amount": "790"
}
