### Profile
POST http://localhost:8080/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlaXMiOjM2MDAsImV4cCI6MTc2NzkzMTYwMCwiaWlkIjoiaW5zXzM4MDhTY1lBQmdqMGN6QkFNTFFiRklXVEpHWiIsInNpZCI6ImFjdF8zODBFSFh1SVdxbmZvWEZwcDQwTlZNMkI0cmoiLCJzdCI6ImFjdG9yX3Rva2VuIn0.m8ujfA0dmLCzKp4HcZXqQCJ7NdBwdk4Kp9qZbubS-AWCTQ2VwE94-BV8OjG0EG5MsyCZmwa12EYuaOB-f-xpGq9Fu--aGR_6DQUyoZT-E-Slk5bLH5CPsaJaVGh5vcFBQxRKwvE1Rho0UoJjqVTkUZ6L9E8dtPwF0mOfZ5IKUGqVUWmZ5WHm6TrLK_dOLxMjbvZ6XpeNo9pDyLEbkY8xGmAH9SWJdO9sC19r6qL4OXLuC3Jdr65VVbVrIyoVNk3As38Fzyc6P5Cztre6VncK9YTmb5X0e9iyWcyTPhhEq75SPSXdtHraqkZEArxQeIKaS8cFx5X5Tb1RYUtJ3MSWgQ

{
    "name":"Huu"
}

### GET Products
GET http://localhost:8080/products


### GET Product By ID
GET http://localhost:8080/products/123

### POST Products
POST http://localhost:8080/products
Content-Type: application/json

{
    "name":"Product",
    "description":"description",
    "price":500.9,
    "stock":200,

}


### GET Product by :id
GET http://localhost:8080/products/123